# Generated by Django 6.0.3 on 2026-03-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem'),
        ('store', '0002_message'),
    ]

    operations = [
    ]
