# Generated by Django 6.0.6 on 2026-06-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cartitem_cart_remove_cartitem_product_and_more 2'),
        ('store', '0006_order_city_order_country_order_zip_code_user_phone_and_more'),
    ]

    operations = [
    ]
